from django.urls import path, include
from rest_framework.routers import DefaultRouter

from recipe import views


router = DefaultRouter()
router.register('tags', views.TagViewset)
router.register('ingredients', views.IngredientViewset)

app_name = 'recipe'

# all urls generated by DefaultRouter will be included at /api/recipe/
urlpatterns = [
	path('', include(router.urls)),
]
